# Generated by Django 4.0.4 on 2022-04-27 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Layoffs (Demitindo)', 'Layoffs'), ('Hiring Freeze (Não está contratando)', 'Hiring Freeze'), ('Hiring (Contratando)', 'Hiring'), ('Ainda não sabemos o status', 'Unknown')], default='Ainda não sabemos o status', max_length=40)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_link', models.URLField(blank=True, max_length=100)),
                ('comentario_thiaguinho', models.TextField(blank=True, default='Teste de texto padrão')),
            ],
        ),
    ]
