# Generated by Django 4.0.4 on 2022-04-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dt_nasc', models.DateField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Trans', 'Trans'), ('Não me identifico', 'Não Me Identifico')], max_length=20)),
                ('status_civil', models.CharField(choices=[('Casado', 'Casado'), ('Solteiro', 'Solteiro'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viuvo')], max_length=20)),
                ('status_clt', models.CharField(choices=[('Ativo', 'Ativo'), ('Desligado', 'Desligado'), ('Contrato Temporário', 'Contrato Temporario')], max_length=30)),
                ('data_contratacao', models.DateField(auto_now=True)),
                ('data_demissao', models.DateField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Layoffs (Demitindo)', 'Layoffs'), ('Hiring Freeze (Não está contratando)', 'Hiring Freeze'), ('Hiring (Contratando)', 'Hiring'), ('Fechando as portas', 'Encerrando Atividades'), ('Ainda não sabemos o status', 'Unknown')], default='Ainda não sabemos o status', max_length=40),
        ),
    ]
