# Generated by Django 4.0.4 on 2022-04-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_operadores_alter_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadores',
            name='cpf',
            field=models.CharField(default='0000000000', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operadores',
            name='data_demissao',
            field=models.DateField(null=True),
        ),
    ]
