# Generated by Django 4.0.4 on 2022-04-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_operadores_cpf_alter_operadores_data_demissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadores',
            name='status_clt',
            field=models.CharField(choices=[('Ativa', 'Ativo'), ('Desligado', 'Desligado'), ('Contrato Temporário', 'Contrato Temporario')], max_length=30),
        ),
    ]
